version: '3.9'

services:
  aptlyui:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-bullseye
    container_name: aptlyui
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ../:/workspace
    
